apiVersion: v1
kind: Pod
metadata:
  name: user-svc-pod
  namespace: shoppingportal
  labels:
    app: user-svc
    zone: prod
    version: v1
spec:
  containers:
  - name: user-svc-cntr
    image: metamagic/msk8-user-service:1.0
    imagePullPolicy: Always
    ports:
     - containerPort: 8080
    livenessProbe:
        httpGet:
          path: /user-svc/live
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 15
    readinessProbe:
        httpGet:
          path: /user-svc/ready
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 15
    
    env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"