apiVersion: v1
kind: Pod
metadata:
  name: user-service-pod
  namespace: shoppingportal
  labels:
    app: user-service
    zone: prod
    version: v1
spec:
  containers:
  - name: user-service-cntr
    image: metamagic/msk8-user-service:1.0
    imagePullPolicy: Always
    ports:
     - containerPort: 8080
    env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"