apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: shoppingportal
  labels:
    app: user-svc
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 8080